
Primeiramente, notei que clicando em "Buscar Comentário" me leva para uma página que não funciona, vide imagem 214777_001.png adicionada junto ao relatório.
Como problema estético é possível notar, na mesma imagem, que os títulos dos botões do menu estão fora de padrão, alguns estão com todas as iniciais maiúsculas enquanto outros estão com iniciais minúsculas.
Também é possível notar que a aba de "Minhas Sessões" tem a quantidade de sessões sendo mostrada, mas os botões "Meus Vídeos" e "Meus Comentários" não possuem tal informação.
E os botões de "Buscar videos", "Meus Videos" e "Subir Video" estão sem acento na palavra vídeo.

Vide imagem 214777_002.png é possível notar que o botão "Ver" tem uma cor branca, mas os botões "Ver" das abas "Meus Videos" e "Minhas Sessões" estão com outras cores (vide imagem 214777_003.png).

Vide imagem 214777_004.png é possível notar que o o botão "Ver" na aba de "Meus Videos" não funciona.

Enquanto deslogado, tentei achar um vídeo com o nome "pipoca" e recebi uma página em branco com erros, vide imagem 214777_005.png, dando esse log de erro:

-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 54646)
Traceback (most recent call last):
  File "/usr/lib64/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib64/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib64/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/home/...../Projeto-MC857-2024-1/processa_comando_http_IMP.py", line 80, in do_GET
    return self.do_geral('GET')
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/...../Projeto-MC857-2024-1/processa_comando_http_IMP.py", line 130, in do_geral
    pag, ses_nova = processa_comando(tipo, ses, dados)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/...../Projeto-MC857-2024-1/processa_comando_http_IMP.py", line 509, in processa_comando
    pag = comando_buscar_videos.processa(ses, cmd_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/...../Projeto-MC857-2024-1/comando_buscar_videos.py", line 38, in processa
    return comando_buscar_videos_IMP.processa(ses, cmd_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/...../Projeto-MC857-2024-1/comando_buscar_videos_IMP.py", line 31, in processa
    erros += util_valida_campo.titulo_de_video(chave, val, False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'util_valida_campo' has no attribute 'titulo_de_video'
-------------------------------------------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------------------------------------------
